version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.15

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...

      - run: go test -v ./...

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  build-main:
    jobs:
      - test
